spring:
  cloud:
    openfeign:
      client:
        config:
          weather:
            url: http://localhost:9090/api/weather
            connect-timeout: 5000
            read-timeout: 5000
resilience4j:
  circuitbreaker:
    instances:
      weather-breaker:
        sliding-window-type: count_based   # Тип скользящего окна: count_based (основан на количестве вызовов)
        sliding-window-size: 5  # Размер скользящего окна: 5 (количество вызовов, учитываемых в окне)
        failure-rate-threshold: 75 # Пороговое значение процента ошибок, при котором срабатывает прерыватель цепи: 75%
        minimum-number-of-calls: 5  # Минимальное количество вызовов, необходимое для оценки статистики
        wait-duration-in-open-state: 10s  #Длительность ожидания в состоянии "open" (прерыватель цепи открыт): 10 секунд
        max-wait-duration-in-half-open-state: 5s  #Максимальная длительность ожидания в состоянии "half-open" (половина открыта): 5 секунд
        automatic-transition-from-open-to-half-open-enabled: true #   Включение автоматического перехода из состояния "open" в "half-open"
        permitted-number-of-calls-in-half-open-state: 2


